# Generated by Django 5.2.7 on 2026-03-25 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('en_service', 'En service'), ('maintenance', 'En maintenance')], default='disponible', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('ingenieur', 'Ingénieur de conception'), ('superviseur', 'Superviseur'), ('pcc', 'PCC'), ('conducteur', 'Conducteur')], default='conducteur', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('fcm_token', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('type_jour', models.CharField(choices=[('JO', 'Jour Ouvrable'), ('JS_JV', 'Samedi/Vendredi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('fichier_source', models.CharField(blank=True, max_length=255)),
                ('importe_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_importes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['type_jour', 'numero'],
                'unique_together': {('numero', 'type_jour')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_course', models.CharField(blank=True, max_length=20)),
                ('origine', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('heure_depart_prev', models.TimeField()),
                ('heure_arrivee_prev', models.TimeField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='gestion.bulletin')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('table_ciblee', models.CharField(max_length=100)),
                ('objet_id', models.IntegerField(null=True)),
                ('details', models.JSONField(default=dict)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('bulletin', 'Bulletin'), ('permutation', 'Permutation'), ('affectation', 'Affectation rame'), ('prise_service', 'Prise de service'), ('absence', 'Absence'), ('general', 'Général')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Permutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_service', models.DateField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('motif_refus', models.TextField(blank=True)),
                ('cible_accepte', models.BooleanField(null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('cible', models.ForeignKey(limit_choices_to={'role': 'conducteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='permutations_recues', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(limit_choices_to={'role': 'conducteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='permutations_demandees', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permutations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_service', models.DateField()),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('confirme', models.BooleanField(default=False)),
                ('heure_confirmation', models.DateTimeField(blank=True, null=True)),
                ('statut_service', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('absent', 'Absent'), ('retard', 'En retard')], default='en_attente', max_length=20)),
                ('motif_absence', models.TextField(blank=True)),
                ('heure_retard', models.DateTimeField(blank=True, null=True)),
                ('affecte_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_effectuees', to=settings.AUTH_USER_MODEL)),
                ('conducteur', models.ForeignKey(limit_choices_to={'role': 'conducteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to=settings.AUTH_USER_MODEL)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='gestion.bulletin')),
                ('rame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.rame')),
            ],
            options={
                'ordering': ['-date_service'],
                'unique_together': {('conducteur', 'date_service')},
            },
        ),
    ]
