# Generated by Django 6.0.3 on 2026-03-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="permutation",
            name="bulletins_echanges",
            field=models.BooleanField(default=False),
        ),
    ]
